#!/usr/bin/env bash
# A script thad displays Best School 10 times and hi after the 9th usign while and if

count=1

while [ $count -lt 10 ]
do 
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((count++))
done
